MODE: 1             # 1: train, 2: test, 3: eval, 4: demo_patch
MODEL: 2            # 1: edge model, 2: inpaint model, 3: edge-inpaint model, 4: joint model
MASK: 3             # 1: random block, 2: half, 3: external, 4: (external, random block), 5: (external, random block, half)
EDGE: 1             # 1: canny, 2: external
NMS: 1              # 0: no non-max-suppression, 1: applies non-max-suppression on the external edges by multiplying by Canny
SEED: 10            # random seed
DEVICE: 1           # 0: CPU, 1: GPU
GPU: [0]            # list of gpu ids
DEBUG: 0            # turns on debugging mode
VERBOSE: 0          # turns on verbose mode in the output console
SKIP_PHASE2: 0      # When training Inpaint model, 2nd and 3rd phases (model 2--->model 3 ) by order are needed. But we can merge 2nd phase into the 3rd one to speed up (however, lower performance).

TRAIN_FLIST: ./datasets/flist/train.flist
VAL_FLIST: ./datasets/flist/val.flist
TEST_FLIST: ./datasets/flist/test.flist

TRAIN_STRUCTURE_FLIST: ./datasets/structure/train.flist
VAL_STRUCTURE_FLIST: ./datasets/structure/val.flist
TEST_STRUCTURE_FLIST: ./datasets/structure/test.flist

TRAIN_EDGE_FLIST:
VAL_EDGE_FLIST:
TEST_EDGE_FLIST:

TRAIN_MASK_FLIST: ./datasets/mask
VAL_MASK_FLIST: ./datasets/mask
TEST_MASK_FLIST: ./datasets/mask

LR: 0.0001                    # learning rate
D2G_LR: 0.1                   # discriminator/generator learning rate ratio
BETA1: 0.0                    # adam optimizer beta1
BETA2: 0.9                    # adam optimizer beta2
BATCH_SIZE: 1                 # input batch size for training
INPUT_SIZE: 256               # input image size for training 0 for original size
SIGMA: 2                      # standard deviation of the Gaussian filter used in Canny edge detector (0: random, -1: no edge)
MAX_ITERS: 2e7                # maximum number of iterations to train the model

EDGE_THRESHOLD: 0.5           # edge detection threshold
L1_LOSS_WEIGHT: 1             # l1 loss weight
FM_LOSS_WEIGHT: 10            # feature-matching loss weight
STYLE_LOSS_WEIGHT: 250          # style loss weight
CONTENT_LOSS_WEIGHT: 0.1        # perceptual loss weight
INPAINT_ADV_LOSS_WEIGHT: 0.1 # adversarial loss weight
LBP_LOSS_WEIGHT: 3

GAN_LOSS: nsgan               # nsgan | lsgan | hinge
GAN_POOL_SIZE: 0              # fake images pool size

SAVE_INTERVAL: 500           # how many iterations to wait before saving model (0: never)
SAMPLE_INTERVAL: 500         # how many iterations to wait before sampling (0: never)
SAMPLE_SIZE: 12               # number of images to sample
EVAL_INTERVAL: 500              # how many iterations to wait before model evaluation (0: never)
LOG_INTERVAL: 100              # how many iterations to wait before logging training status (0: never)
PRINT_INTERVAL: 10            # how many iterations to wait before terminal prints training status (0: never)
